### ISSUE TITLE
Show students' learning request on waiting list, next to their name

### ISSUE THREAD

**Issue by AnwenW** [codebar/planner#1525]
When a student has a spot on the workshop, organisers can see details of what they have signed up for. It would be helpful to also display this information for students on the waiting list — to help organisers balance students with available coaches.

<img width="535" alt="Screenshot 2021-05-04 at 15 11 47" src="https://user-images.githubusercontent.com/26367462/117018508-74fe1500-acec-11eb-9d44-e8be36a341c4.png">

**Comment by despo** [comment]
This happened because the field that contained details about the tutorial was remapped to `notes` and the newly introduced tutorial field was never added to the view.

To resolve, this partial should be updated to also include tutorial

https://github.com/codebar/planner/blob/master/app/views/admin/workshop/_waiting_list.html.haml#L29
