### ISSUE TITLE
Be able to filter sponsors for just one chapter

### ISSUE THREAD

**Issue by jftsang** [codebar/planner#1746]
## To do 📋

* [ ] Claim this issue (comment below, or assign yourself if you are part of the codebar org)
* [ ] Fork and clone the repository
* [ ] Update the relevant files. Follow the steps to fix section in this issue.
* [ ] Commit your changes as one commit. Use the title of this issue as your commit message
* [ ] Submit a pull request
* [ ] Mention this issue in the PR description by including it's number
* [ ] Have your pull request reviewed & merged by a codebar team member

**Comment by brunogirin** [comment]
I can see a few use cases for this:

## New workshops form

The list of sponsors should be filtered according to the chapter that is selected at the top. This is particularly important here as the list is long and we have some sponsors that have multiple entries because they sponsor us in multiple locations: if it's not filtered, we risk choosing the wrong one.

![Screenshot 2022-05-03 105033](https://user-images.githubusercontent.com/216028/166434378-dee7915d-4789-4311-aa09-1bc704344024.png)

## Sponsor list

The list of sponsors available in the admin could have a way to filter.

![Screenshot 2022-05-03 105027](https://user-images.githubusercontent.com/216028/166435829-8fe01e05-767b-47b8-abf2-b87f7bd2e996.png)

## Chapter menu

The admin menu for a chapter could have a "View {chapter name} sponsors" option that would open a filtered list of sponsors.

![Screenshot 2022-05-03 105142](https://user-images.githubusercontent.com/216028/166435928-3e71e66d-5f18-4d8a-9ed5-78a215f87326.png)
