### ISSUE TITLE
Alignment of button and dropdown

### ISSUE THREAD

**Issue by KimberleyCook** [codebar/planner#1813]
## Description of the issue 📄
The alignment of the add button and dropdown on the admin events page is incorrect, they should be next to each other.

## Screenshots 📷
<img width="1188" alt="Screenshot 2022-09-23 at 11 31 05" src="https://user-images.githubusercontent.com/2683270/191932217-4eafeb18-609d-414a-8765-8e8128cc523b.png">

## To do 📋

* [ ] Claim this issue (comment below, or assign yourself if you are part of the codebar org)
* [ ] Fork and clone the repository
* [ ] Update the relevant files. Follow the steps to fix section in this issue.
* [ ] Commit your changes as one commit. Use the title of this issue as your commit message
* [ ] Submit a pull request
* [ ] Mention this issue in the PR description by including it's number
* [ ] Have your pull request reviewed & merged by a codebar team member

**Comment by tbutterwith** [comment]
This is caused by a long value in the text box. We've got 3 options for handling this (within the Bootstrap framework used on the site):
1. Leave it as it is. The columns are set to auto expand and this will only affect events where someone has a long name. You could also looking into capping the number of characters displayed in the text box
2. Commit to the add button on a new line and style it appropriately (see img below)
3. Set a width on the column so it doesn't auto-size, which means the Add button will always be offset right (see img2 below)

### Option 2:
![image (9)](https://user-images.githubusercontent.com/6391616/192484795-23ea08e9-4041-4922-b83a-2eaaa383be21.png)

### Option 3:
![image (10)](https://user-images.githubusercontent.com/6391616/192484803-c5edbf85-14e9-4567-8f04-4ab9517b5617.png)
