### ISSUE TITLE
Host accessiblity

### ISSUE THREAD

**Issue by despo** [codebar/planner#326]
Recently we've had more demand for accessible venues. We should be capturing and displaying if a venue is accessible.

The information should be stored on the Sponsor model and rendered on the events listing and invitation pages.

**Comment by stschwark** [comment]
What information about accessibility do we need to capture. Is this a boolean or is there more to it?

Also, I would suggest to add this to the Address model as that's what represents the venue.

**Comment by despo** [comment]
@stschwark it might be worth adding an accessibility_note as well in case there are instructions going along e.g. lift location, 

You are right, it should probably go on the address.

**Comment by stschwark** [comment]
Just saw that #212 also raises some overlapping requirements, i.e.:
- extra details if we're in an awkward location (hard to find/bad signage/etc)
- information about security when we have workshops at locations that have restrictive building policies
which could also be added to the Address model once rather than for each workshop.

So maybe an accessibility flag plus a general note?

**Comment by deniseyu** [comment]
Commenting here to flag that this feature is still very much desired. A free-text field that supports HTML rendering will do the trick; the content can be nailed down later.
