### ISSUE TITLE
Flash alert for users who have first or last name as empty string

### ISSUE THREAD

**Issue by deniseyu** [codebar/planner#406]
It seems like, although first and last name are checked on Member creation, people can go back and edit their profiles so their first and/or last names are blank.

If people have names as a blank string, it is impossible for organisers to add them manually to a workshop, event, or Monthly.

People who have either their first or last name as a string should see a flash alert on their dashboard along the lines of "We noticed that you have not filled out your first and last name. Please update your profile here (link to /profile) -- until then, you will not have full ability to attend our events!"

Desired-but-not-required-for-this-ticket: Investigate why the validation is failing on the member update action, and reimplement it so it is not possible to set either to an empty string.

**Comment by clairgriffiths** [comment]
Is anyone working on this? If not, I'd love to give it a go...

**Comment by KimberleyCook** [comment]
@clairgriffiths No, please go ahead :)

**Comment by KimberleyCook** [comment]
@clairgriffiths did you start looking into this?

**Comment by clairgriffiths** [comment]
I did, but I can't replicate the issue, each time I try to edit a profile to save it with an empty string it throws a 'can't be blank' message and won't let me save. (Sorry, meant to catch someone at a Codebar to talk it through but always got waylaid)

**Comment by KimberleyCook** [comment]
Ah it must've been done then, I'll close it. Thanks

**Comment by matyikriszta** [comment]
I couldn't recreate this issue when updating the user profile either. I think the issue happens when we create the user through Github auth -- on Github you can have a profile without the Name field filled in, and that is where we are getting the data. Might be worth looking at the user creation logic and making sure you have to fill those fields in if you don't have a name specified on Github. Is it worth opening a new issue or reopening this one?
