### ISSUE TITLE
Update meta data in emails

### ISSUE THREAD

**Issue by zaccolley** [codebar/planner#560]
It'd be nice if we had the meta data in emails for workhop confirmation that allows Gmail/Inbox to automatically add it your calendar.

**Comment by MikeRogers0** [comment]
https://developers.google.com/gmail/markup/reference/event-reservation - This is the markup you're referring to correct?

**Comment by zaccolley** [comment]
Yep, literally having a look now aha

**Comment by richardwestenra** [comment]
@zaccolley How did you get on with this? I started looking into it (because this issue bugs me too), and I found what I think is the relevant file (app/views/meeting_invitation_mailer/attending.html.haml) but I got stuck because I'm not sure how to echo the relevant data (e.g. `host_address`) so I can inspect it, nor how to test these emails easily.

**Comment by zaccolley** [comment]
I put in the meta data in, sent the emails and it didn't work.

Happy for someone else to have a go.

**Comment by MikeRogers0** [comment]
@zaccolley Did you register the markup with Google also ( https://developers.google.com/gmail/markup/registering-with-google )?

**Comment by zaccolley** [comment]
ooo - No i didnt

**Comment by docljn** [comment]
Based on the emails I'm receiving as a coach, the update appears to have been made.  Oddly, gmail gives me a quicklink to track a dhl package from the email too, so...?
<img width="1064" alt="screen shot 2018-08-19 at 00 29 44" src="https://user-images.githubusercontent.com/28825519/44303983-0499e480-a347-11e8-8a45-b4792e0195d1.png">

**Comment by docljn** [comment]
Thanks @zaccolley
