### ISSUE TITLE
[Accessibility] Alt tags on images

### ISSUE THREAD

**Issue by zaccolley** [codebar/planner#584]
Some images don't have suitable `alt` tags, these are used when the visual image can't be.

For example on the home page:

`<img class="th radius" title="Richard Westenra (he/him)" src="https://secure.gravatar.com/avatar/db5febefdbd146a0aedc71fb614b5b12?size=26&amp;default=identicon" alt="Db5febefdbd146a0aedc71fb614b5b12?size=26&amp;default=identicon">
`

Here the alt tag could be "Richard Westenra" instead.

**Comment by docljn** [comment]
Hello, 
I have started the process of adding alt tags where possible, and made a pull request.  I cannot find any other images without alt tags, but that may be my lack of experience, so do please check!
Kind regards.

**Comment by zaccolley** [comment]
Thanks! :raised_hands:

**Comment by docljn** [comment]
@KimberleyCook 
One thing I have noticed since the change went live is that the Sponsor logos on the events page don't have useful alt information, although they do have the alt tag.  I hope that isn't because I used the wrong variable to find the sponsor name...

e.g. Red Badger at the moment
<img class="sponsor" src="https://assets.codebar.io/b//uploads/sponsor/avatar/316/RB_Screen_Logos_Artwork-02__1___1_.png" alt="Rb screen logos artwork 02  1   1 ">

**Comment by KimberleyCook** [comment]
I've not deployed to master yet so you won't see the amend just yet.

**Comment by docljn** [comment]
Phew!
