### ISSUE TITLE
[accessibility]Tab order - side nav still tab focusable when off page

### ISSUE THREAD

**Issue by BNewing** [codebar/planner#609]
At the moment, if you try to use the site with just a keyboard, the side nav isn't great. Even though it's hidden off the page initially, it's still focusable by tab. So if you're tabbing through the top nav bar, once you get through that the tab focus will disappear away off of the page. 

One possible fix could be this, from a video we watched at work the other day:

**https://www.youtube.com/watch?v=fGLp_gfMMGU**

**Comment by richardwestenra** [comment]
I just had a look into this: Apparently this nav menu is built with Zurb Foundation, which handles all the JS for this automatically without any custom scripts needing to be written. However this means we don't have any control over it :(

[Their documentation](https://foundation.zurb.com/sites/docs/v/5.5.3/components/offcanvas.html#accessibility) specifically says that it's not accessible, but they don't propose a solution :((((

I think the best solution, unfortunately, would be to add an extra onclick listener to the menu button, and toggle `hidden` or `display:none` or `tabindex="-1"` or something like that, on the nav menu. Obviously this is an extremely shitty solution - especially since this menu is animated, so any solution which affects the menu's visibility would need a delay/debounce so it doesn't affect the closing animation.

**Comment by BNewing** [comment]
Nooo that is a shame. Is rewriting the menu with our own code from scratch and putting that in possible instead? I'd be up for giving that a go, if it's possible! 

Otherwise we might have to go with that route nuuu

**Comment by richardwestenra** [comment]
Yeah that's doable. Depends how much energy you want to put in. I think just adding a new listener on top of the existing one is probably easier...

I might have a quick crack at it.

**Comment by richardwestenra** [comment]
@BNewing Done. I did a minimum-effort approach, rather than rebuilding the entire menu's toggle functionality: I really don't think it's worth investing a lot of time in this fix, when the website might (hopefully) get a full redesign in a few months' time anyway.

**Comment by BNewing** [comment]
Looks good! I didn't know the site was being redesigned - in that case it does make sense! I have been looking for a use case to try out that idea in that video but I think you're right, and I never have as much time as I think I do :P
