### ISSUE TITLE
Implement send-only-one barrier for meetings/monthlies emails 

### ISSUE THREAD

**Issue by kkavita92** [codebar/planner#701]
## Description of the issue 📄

Currently, there isn't any barrier to limiting invitation emails to be sent only once (which already exists for weekly workshops) for meetings/monthlies. 

## To do 📋

* [ ] Claim this issue (comment below, or assign yourself if you are part of the codebar org)
* [ ] Fork and clone the repository
* [ ] Update the relevant files. Follow the steps to fix section in this issue.
* [ ] Commit your changes as one commit. Use the title of this issue as your commit message
* [ ] Submit a pull request, make sure you mention #codebar24PR2017 in the description
* [ ] Mention this issue in the PR description by including it's number
* [ ] Have your pull request reviewed & merged by a codebar team member

**Comment by matyikriszta** [comment]
@kkavita92 seems like this feature has been implemented, @despo can you verify this?

**Comment by despo** [comment]
@matyikriszta unfortunatelly it has not. There is an `emails_sent` flag on the `Meeting` model, set when emails go out to prevent them from being resent, but I don't believe that is working as expected.

This week more than one emails were sent out and what I think happened (and likely what has happened in the past) is that the app fell over when trying to immediately email everyone subscribed to London, and as a result it never got to the line where the flag is set, [here](https://github.com/codebar/planner/blob/master/app/controllers/admin/meetings_controller.rb#L57) to be specific.

Since there is a `MeetingInvitation` model in place I would tweak the Meeting controller to generate the MeetingInvitations when emails are sent out, so we can keep track and never be able to send duplicates. Similar to how workshop invitations behave.

**Comment by despo** [comment]
Closing as there is a newer issue with more details about how to tackle this #1317
