### ISSUE TITLE
Suggestion: Add `React Project` to projects to work on 

### ISSUE THREAD

**Issue by zurda** [codebar/planner#909]
## Description of the issue 📄
Currently the Codebar form does not include `React Project`, yet the topic is available in London and West London meetups.  A person who wants to work on React should update the hosts at the meetup. 

## Screenshots 📷
<img width="410" alt="screenshot 2019-01-15 at 20 02 09" src="https://user-images.githubusercontent.com/16784959/51206659-86933700-1900-11e9-9434-9297f5fa7e23.png">

## Steps to fix 🛠
Add `ReactJS project` to list of projects. 

## To do 📋
* [ ] Claim this issue (comment below, or assign yourself if you are part of the codebar org)
* [ ] Fork and clone the repository
* [ ] Update the relevant files. Follow the steps to fix section in this issue.
* [ ] Commit your changes as one commit. Use the title of this issue as your commit message
* [ ] Submit a pull request
* [ ] Mention this issue in the PR description by including it's number
* [ ] Have your pull request reviewed & merged by a codebar team member

**Comment by KimberleyCook** [comment]
Hey Zurda, thanks for your suggestion. This list however comes from our tutorials over on http://tutorials.codebar.io/, and since we don't have a React tutorial we shouldn't be adding it to our list set.

**Comment by zurda** [comment]
Thanks Kimberley, sorry about that. 
I know there's agreement that the react documentation tutorial is pretty good for beginners. Is there a possibility to add it as a tutorial, or do all tutorials must be originally written by codebar?

**Comment by matyikriszta** [comment]
@zurda a little correction here, some of these come from the list of tutorials on tutorials.codebar.com but some of them are common topics people work on (e.g. Rails project & Javascript project). There is a `Tutorial` model in the app, it does not have an interface but we could add a React project tutorial from the console. Since there are a lot of people working on React projects I'd support adding it to the list of available topics. @KimberleyCook what do you think?

**Comment by zurda** [comment]
Thanks for clarifying @matyikriszta 🌻. If this workaround is agreed and possible I'm happy to claim this issue and create a PR

**Comment by matyikriszta** [comment]
@KimberleyCook bumping this issue, it would be good to close it. I'm just waiting for you to confirm it is fact OK to add React project to the list of topics. We do have a ton of people working on react and we do have topics for Rails and Javascript projects.

**Comment by KimberleyCook** [comment]
I don't think we should add it. We've never added a JavaScript library before so why would we now? In a few years React will not be a thing people everyone wants to learn and it'll eb soemthing else.

Plus React is big in some places (I.E London) whereas many chapters never have students who learn React.

**Comment by kodikos** [comment]
Technically Rails is a library on top of Ruby, so I think there is precedent for including frameworks on top of languages. I'd hazard the distinction can be lost on students at times when they pick an item from the drop-down. 
I think if there's enough deviation from a straight-forward language that it can't be taught easily by a coach who isn't versed in it, then it could be worth differentiating in the drop-down. I have noticed the chap that does the pairing in the central London codebar calls out React separately from Javascript.
What is the drop-down helping with? I thought it was for pairing.

**Comment by matyikriszta** [comment]
@kodikos yes, it was to help with pairing, if we know what a student wants to work on in advance it makes it easier for us to put them in a group with other students.

Specifically with React, since it's different enough from vanilla JS it helps us to know the student is planning to work on React specifically as opposed to just Javascript (as it might require us to find a coach with specialized React knowledge). Otherwise we will have to remember to ask the students at the workshop what kind of Javascript project they will want to work on and come up with groupings on the spot which is harder.

Re: React disappearing in a few years, I think it has proven it has staying power, if for nothing else the huge corporation behind it to push it.

Furthermore I agree if we say no to React we should probably remove Rails as well since as you pointed it out it's a framework and not a language. Although I do think React is popular enough that it deserves a spot if for example Rails is on there (which we don't get much anymore).

**Comment by KimberleyCook** [comment]
I don't think we should have Rails in our list either.

But if you both think we should add then it's an easy update, and we can always remove it at a later date.

**Comment by despo** [comment]
As we have diverted from only using our tutorials and React seems to now be a big part of what students are working on I hae added it to our database. Closing issue.
