### ISSUE TITLE
When sending out eligibility or attendance emails make sure the relevant chapter are cc'd in

### ISSUE THREAD

**Issue by KimberleyCook** [codebar/planner#955]
## Description of the issue 📄
When sending out eligibility or attendance emails make sure the relevant chapter are cc'd in.

## To do 📋

* [ ] Claim this issue (comment below, or assign yourself if you are part of the codebar org)
* [ ] Fork and clone the repository
* [ ] Update the relevant files. Follow the steps to fix section in this issue.
* [ ] Commit your changes as one commit. Use the title of this issue as your commit message
* [ ] Submit a pull request
* [ ] Mention this issue in the PR description by including it's number
* [ ] Have your pull request reviewed & merged by a codebar team member

**Comment by JacobAbrahamShopify** [comment]
@KimberleyCook do you mind specifying which emails your referring to? I am getting familiar with the codebase so im not sure what `eligibility` and `attendance` emails are. do you mind specifying the subject line for these emails? 🙏

**Comment by KimberleyCook** [comment]
Hey @JacobAbrahamShopify each chapter has it's own email (E.G london@codebar.io, brighton@codebar.io, barcelona@codebar.io) it would be great if the relevant email of the chapter the person i subscribed to gets cc'd into the email. Currently it's only hello@codebar.io that gets cc'd.

**Comment by JacobAbrahamShopify** [comment]
im trying to submit a PR but i get 
```
ERROR: Permission to codebar/planner.git denied to JacobAbrahamShopify.
fatal: Could not read from remote repository.
```
anything i need to do for this?

**Comment by GarySiu** [comment]
Hello @JacobAbrahamShopify, it looks like you're trying to push directly to codebar's repo. You should push to your fork and then create a pull request from your fork.

https://help.github.com/en/articles/creating-a-pull-request-from-a-fork

**Comment by matyikriszta** [comment]
@KimberleyCook one thing just occurred to me re: this issue. A person can be subscribed to more then one chapter, what should happen to these emails in that case? Which chapter gets the email or should all of them be CCd in?

@JacobAbrahamShopify as @GarySiu said you are pushing directly to the codebar repo which we don't allow. If you'd like to contribute you'll have to fork the repo, push to your own forked repo and open a PR against the original repo from there. Please check out our contributing guididelines for more details: https://github.com/codebar/planner/blob/master/CONTRIBUTING.md

**Comment by yihyang** [comment]
Hi there can I confirm that this issue is a duplication of https://github.com/codebar/planner/issues/746 ?

**Comment by notapatch** [comment]
@despo as pointed out by yihyang this looks like a duplicate of #746.

**Comment by despo** [comment]
Closed #746 which was indeed a dup.

**Comment by Indrajitnaiya09** [comment]
@despo @notapatch @KimberleyCook @matyikriszta is this issue is still open? Then I'm planning to pick it up.

Even I have the same doubts as @matyikriszta https://github.com/codebar/planner/issues/955#issuecomment-522352921 what to do In this scenario?

**Comment by matyikriszta** [comment]
@Indrajitnaiya09 yes, this issue is still open. Here's what I think we should do in case a member is subscribed to more than one chapter.

First, I think we should handle eligibility and attendance emails separately (as they have slightly different implications etc.). I think we should first focus on attendance emails. Here's how I think this could work:

1. Extend the `AttendanceWarning` model so we can track which chapter the warning was sent for.
2. Add a dropdown to the send attendance email flow with the names of all the chapters a member is subscribed to. Ensure organisers have chosen a chapter before sending the email. Unless the member is subscribed to only one chapter, in that case just send the email to the "default" chapter.
3. When sending the email, save which chapter if was sent for and use that chapters email address as the sender (CC in hello@codebar.io).
4. Add a section to the admin member profile page that lists all the attendance warning emails they have received and which chapter it was sent for.
5. Update the confirmation step for sending subsequent attendance warning emails.
