### ISSUE TITLE
link to our open collective on website and inside repo

### ISSUE THREAD

**Issue by khamiltonuk** [codebar/planner#997]
## Description of the issue 📄
Can we link to our opencollective page from the site? 
Unlike the current stripe integration it allows monthly contributions
https://opencollective.com/codebar
- potentially removing the stripe integration or working along side as an alternative

### on the website
![Screenshot 2019-06-26 at 14 40 53](https://user-images.githubusercontent.com/4013283/60180486-6efd9a00-9820-11e9-97ec-f6127e455e69.png)
### in the repo
![Screenshot 2019-06-26 at 14 35 59](https://user-images.githubusercontent.com/4013283/60180204-c0f1f000-981f-11e9-9027-eed5b5950b2d.png)

## To do 📋

* [ ] Claim this issue (comment below, or assign yourself if you are part of the codebar org)
* [ ] Fork and clone the repository
* [ ] Update the relevant files. Follow the steps to fix section in this issue.
* [ ] Commit your changes as one commit. Use the title of this issue as your commit message
* [ ] Submit a pull request
* [ ] Mention this issue in the PR description by including it's number
* [ ] Have your pull request reviewed & merged by a codebar team member

**Comment by matyikriszta** [comment]
@khamiltonuk we have added the Sponsor button to the repo now (screenshot 1) and added a How to support codebar section the homepage with a link to Opencollective (screenshot 2). The donation page has been repurposed to be used as payment page for job postings (which are not donations but payments for a service we offer). Since we have addressed both of the points raised in this ticket I'm going to close it.

<img width="1440" alt="Screenshot 2020-09-28 at 8 10 22 pm" src="https://user-images.githubusercontent.com/5873816/94508517-f9247300-01c6-11eb-8a9a-6757f9ad2855.png">

<img width="1440" alt="Screenshot 2020-09-28 at 8 13 16 pm" src="https://user-images.githubusercontent.com/5873816/94508571-10636080-01c7-11eb-9ed6-9b4047ede0f1.png">
